steps:
  # --- 1. Build Frontend Image ---
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c' 
      - |
        docker pull asia-northeast1-docker.pkg.dev/myragapp-479606/myragapp-repo/myragapp-frontend:latest || true && \
        docker build --cache-from asia-northeast1-docker.pkg.dev/myragapp-479606/myragapp-repo/myragapp-frontend:latest \
        -t asia-northeast1-docker.pkg.dev/myragapp-479606/myragapp-repo/myragapp-frontend:latest \
        --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=$$NEXT_PUBLIC_FIREBASE_API_KEY \
        --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN \
        --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID=$$NEXT_PUBLIC_FIREBASE_PROJECT_ID \
        --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET \
        --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID \
        --build-arg NEXT_PUBLIC_FIREBASE_APP_ID=$$NEXT_PUBLIC_FIREBASE_APP_ID \
        --build-arg NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID \
        .
    secretEnv: 
      - 'NEXT_PUBLIC_FIREBASE_API_KEY'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID'
      - 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID'
    id: 'Build Frontend'
    waitFor: ['-']

  # --- 2. Build Backend Image ---
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull asia-northeast1-docker.pkg.dev/myragapp-479606/myragapp-repo/myragapp-backend:latest || true && docker build --cache-from asia-northeast1-docker.pkg.dev/myragapp-479606/myragapp-repo/myragapp-backend:latest -t asia-northeast1-docker.pkg.dev/myragapp-479606/myragapp-repo/myragapp-backend:latest -f backend/Dockerfile .']
    id: 'Build Backend'
    waitFor: ['Build Frontend'] # Wait for Frontend to finish

  # --- 3. Push Images ---
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/myragapp-479606/myragapp-repo/myragapp-frontend:latest']
    id: 'Push Frontend'
    waitFor: ['Build Frontend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/myragapp-479606/myragapp-repo/myragapp-backend:latest']
    id: 'Push Backend'
    waitFor: ['Build Backend']


  # --- 4. DB Migration ---
  - name: 'asia-northeast1-docker.pkg.dev/myragapp-479606/myragapp-repo/myragapp-frontend:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'HOME=/tmp npm_config_cache=/tmp/npm-cache DATABASE_URL=$(echo $$DATABASE_URL | sed "s/:6543/:5432/") npx -y prisma@6.19.1 migrate deploy'
    secretEnv: ['DATABASE_URL']
    id: 'DB Migration'
    waitFor: ['Push Frontend']

  # --- 5. Deploy Frontend to Cloud Run ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'myragapp-frontend'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/myragapp-479606/myragapp-repo/myragapp-frontend:latest'
      - '--region'
      - 'asia-northeast1'
    id: 'Deploy Frontend'
    waitFor: ['Push Frontend', 'DB Migration']

  # --- 6. Deploy Backend to Cloud Run ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'myragapp-backend'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/myragapp-479606/myragapp-repo/myragapp-backend:latest'
      - '--region'
      - 'asia-northeast1'
    id: 'Deploy Backend'
    waitFor: ['Push Backend']

images:
  - 'asia-northeast1-docker.pkg.dev/myragapp-479606/myragapp-repo/myragapp-frontend:latest'
  - 'asia-northeast1-docker.pkg.dev/myragapp-479606/myragapp-repo/myragapp-backend:latest'

availableSecrets:
  secretManager:
  - versionName: projects/myragapp-479606/secrets/database_url/versions/latest
    env: 'DATABASE_URL'
  - versionName: projects/myragapp-479606/secrets/next_public_firebase_api_key/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_API_KEY'
  - versionName: projects/myragapp-479606/secrets/next_public_firebase_auth_domain/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
  - versionName: projects/myragapp-479606/secrets/next_public_firebase_project_id/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_PROJECT_ID'
  - versionName: projects/myragapp-479606/secrets/next_public_firebase_storage_bucket/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'
  - versionName: projects/myragapp-479606/secrets/next_public_firebase_messaging_sender_id/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'
  - versionName: projects/myragapp-479606/secrets/next_public_firebase_app_id/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_APP_ID'
  - versionName: projects/myragapp-479606/secrets/next_public_firebase_measurement_id/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID'




