name: jibunAI-ios
options:
  bundleIdPrefix: com.yasu
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: 15.0
  groupSortPosition: top

targets:
  jibunAI-ios:
    type: application
    platform: iOS
    sources:
      - path: jibunAI-ios
      - path: LineAuthManager.swift
      - path: jibunAI.storekit
      - path: openapi.json
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yasu.jibunAI-ios
        INFOPLIST_FILE: jibunAI-ios/Info.plist
        IPHONEOS_DEPLOYMENT_TARGET: 17.0
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1,2 # iPhone & iPad
        ENABLE_PREVIEWS: YES
        SWIFT_VERSION: 5.0
