name: jibunAI-ios
options:
  bundleIdPrefix: com.yasu
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: 15.0
  groupSortPosition: top

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    majorVersion: 10.29.0
  LineSDK:
    url: https://github.com/line/line-sdk-ios-swift
    majorVersion: 5.0.0
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    majorVersion: 7.0.0
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios
    majorVersion: 5.0.0
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    majorVersion: 7.0.0
  Lottie:
    url: https://github.com/airbnb/lottie-ios
    majorVersion: 4.0.0

targets:
  jibunAI-ios:
    type: application
    platform: iOS
    sources:
      - path: jibunAI-ios
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yasu.jibunAI-ios
        INFOPLIST_FILE: jibunAI-ios/Info.plist
        CODE_SIGN_ENTITLEMENTS: jibunAI-ios/jibunAI-ios.entitlements
        IPHONEOS_DEPLOYMENT_TARGET: 17.0
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1,2 # iPhone & iPad
        ENABLE_PREVIEWS: YES
        SWIFT_VERSION: 5.0
        OTHER_LDFLAGS: $(inherited) -ObjC
        DEVELOPMENT_TEAM: ""
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseMessaging
      - package: Firebase
        product: FirebaseCrashlytics
      - package: LineSDK
        product: LineSDK
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: RevenueCat
        product: RevenueCat
      - package: Kingfisher
        product: Kingfisher
      - package: Lottie
        product: Lottie
